In [5]:
### To change directory: ###
#import os
#os.getcwd()
#os.chdir()

## Loading packages
In this section we point out differences between Python and $LaTeX$. We first import the useful libraries. 
Remember that we can use
```python
from numpy import *
```
to avoid writing the package name. 
Or, we can use the namesapce
```python
from pylab import *
```
which incldes Numpy, Scipy, and Matplotlib



In [6]:
import numpy as np

#from numpy import *
#from sympy import *

In [4]:
### Note that string can be enclosed with either single quotes or double quotes. For example, both of the below are valid.
my_string = 'This is a string with single quotes'
print (my_string)
my_string = "This is a string with double quotes"
print (my_string)

This is a string with single quotes
This is a string with double quotes


### Techniques of print function
- Note that if we see statements like `print x`, then the code is written in Python 2! This is syntax of Python 2 and we use Python 3. 
- In print(), we can use `sep=''` and `end=''` to control the seperator and end of line procedure!

In [5]:
arr=np.arange(10)
# ways to print both string and numbers
print("arr =", arr) #1st method
print("arr = " + str(arr))
print("Hello","world", 123, sep=' xxx ', end=' ')

## The following is a good print() example
def fib(n):    # write Fibonacci series up to n
    """Print a Fibonacci series up to n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()    # used to add a new line

# Now call the function we just defined:
fib(2000)

arr = [0 1 2 3 4 5 6 7 8 9]
arr = [0 1 2 3 4 5 6 7 8 9]
Hello xxx world xxx 123 0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


### Difference between range and np.arange
- their functions are the same: create numbers from $[a,b)$, with `range(a,b)`. However, `range(a,b)` returns a list (since it is a built-in python function!), whereas `np.arange(a,b)` returns an n-d array.
- note: `range(0,20,2)` means that {0,2,4,6,...,18}

In [9]:
A=range(1,10)
#print(type(A))
B=np.arange(1,10)
#print(A.shape) #error! since A is not an array
print(B.shape)
for i in range (0,20,2):
    print(i)

<class 'range'>
(9,)
0
2
4
6
8
10
12
14
16
18


### Misc. 
- to do block comments, use """ comment """
- remember that to use exp, we should use np.exp, not math.exp, since np.exp supports vector input
- to check the documentation of a function, use `np.FUNCTION_NAME?`


In [7]:
"""
This is a block comment
"""
print(3)

3


### Iteration constructs
- the `for` loop syntax is `for i in []'

In [8]:
for i in range(1,3):
    print(i)

1
2


### Matrix Creation functions
- `arange(20,30)` create a *rank-1* array $[20,21,\dots,29]$. Note that there are 10 elements in the array and the last element (i.e., 30) is not included. 
    - Note that python has a built-in function (`range()`) that achieves the same purpose, but the result of `range()` is a list in Python 2 (or iterator object in Python 3). 
- `eye(3)` creates the 3-by-3 identity matrix, just like in Matlab
- `ones((3,4))` creates a 3-by-4 matrix with all elements being 1, just like in Matlab
    - Note that we need the argument to be (3,4), with paranthesis.
- `zeros((3,4))`  creates a 3-by-4 zero matrix
- Creating matrices by random function:
    - `random.rand(3,4)` creates a 3-by-4 matrix whose entries are in $U(0,1)$.
    - `random.uniform(1,10,(3,4))` creates a 3-by-4 matrix whose entries are in $U(1,10)$.
    - `random.randn(3,4)` creates a 3-by-4 matrix whose entries are drawn from standard Normal $N(0,1)$.
    - `random.randint(1,10,(3,4))` creates a 3-by-4 matrix whose entries are drawn from Discrete Uniform distribution $\{1,\dots,9\}$.
    
- We can use `\n` in `print()` for a new line

In [9]:
print("np.zeros((3,4)) returns \n" + str(np.zeros((3,4))) +'\n'  )
print("np.arange(10) returns \n" + str(np.arange(10))+'\n')
print("shape(np.arange(10)) = " + str(np.shape(np.arange(10)))+'\n')
print("eye(3) returns \n" + str(np.eye(3))+'\n')
print("ones((3,4)) returns \n" + str(np.ones((3,4)))+'\n')
#np.ones(3,4)
print("random.rand(3,4) returns \n" + str(np.random.rand(3,4))+'\n')
print("random.uniform(1,10,(3,4)) returns \n" + str(np.random.uniform(1,10,(3,4)))+'\n')
print("random.randn(3,4) returns \n" + str(np.random.randn(3,4))+'\n')
print("random.randint(1,10,(3,4)) returns \n" + str(np.random.randint(1,10,(3,4)))+'\n')
#fancy way to use a for loop
A=np.array([ range(i, i+3) for i in [2,4,6] ]) # nested lists result in multidimensional arrays
print(A)
print (A.shape)

#Note that 
#y=np.arange(11,20)
#print("content of y:" + str(y))
#print(x*y)

np.zeros((3,4)) returns 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.arange(10) returns 
[0 1 2 3 4 5 6 7 8 9]

shape(np.arange(10)) = (10,)

eye(3) returns 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

ones((3,4)) returns 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

random.rand(3,4) returns 
[[0.14862346 0.80438158 0.08791702 0.7236038 ]
 [0.27552509 0.19905673 0.73760053 0.90821586]
 [0.58192593 0.27136067 0.15051898 0.9431438 ]]

random.uniform(1,10,(3,4)) returns 
[[5.32999853 4.827613   3.10504532 3.53231154]
 [3.18431716 8.72580436 9.38079856 5.718419  ]
 [2.48197535 5.97301999 7.12230282 5.43824373]]

random.randn(3,4) returns 
[[ 0.75716927  0.33907039 -1.4881188   1.59380233]
 [-1.12923778  2.35653533  0.41908924  0.04853989]
 [ 0.14963697  0.00601954  0.69408535  0.02394667]]

random.randint(1,10,(3,4)) returns 
[[6 2 6 3]
 [2 4 9 6]
 [1 9 1 4]]

[[2 3 4]
 [4 5 6]
 [6 7 8]]
(3, 3)


## Shape of Arrays
- `np.array([ [1,2], [3,4]  ])` creates a matrix with shape (2,2). 
- `np.array([ [1,2,2]  ])` creates a row vector with shape (1,3). 
- **Important**: if we see two pairs of brackets, then the resulting array is 2d. Similar, if there are n pairs, then nd array.
    - Note that 1d array is called *rank-1 array*, 2d array is a matrix, 3d or above are tensor.
    - Even when we're going to create a vector, we should create a 2d array, eg: np.array([ [1,2,2] ]). 
- `shape(A)` or `A.shape` returns the dimensions of the array. 
  - In fact, `A.shape` is preferred because we usually have too many paranthesis. 
  - However, sometimes we cannot use A.shape! EG: `shape(array([ [1,2,2]  ]))` would requires us to create a temp array first!
- To get the # of rows of a matrix, do `A.shape[0]`
- `A.reshape(A.shape[0]*A.shape[1],1)` reshapes A to a column vector of shape (A.shape[0]*A.shape[1],1)

In [10]:
myMat=np.array([ [1,2], [3,4]  ])
print("shape of array([ [1,2], [3,4]  ]) ) is: " + str(myMat.shape) )
myVec=np.array([ [1,2,2] ])
print("shape of array([ [1,2,2] ])) is: " + str(myVec.shape))
print(myMat.reshape(myMat.shape[0]*myMat.shape[1],1))


shape of array([ [1,2], [3,4]  ]) ) is: (2, 2)
shape of array([ [1,2,2] ])) is: (1, 3)
[[1]
 [2]
 [3]
 [4]]


### Math Stuff
- The constants are stored in `math` module, which is always available without any import
    - More info: https://docs.python.org/2/library/math.html
    - However, we should always use the math functions available in the `numpy` library, because they allow for array input!
    - In fact, we should avoid using the math library, because functions definied there can deal with real numbers as input only.
- Constants:
    - `pi` and `exp(1)`
- logic operators:
    - `a and b` and `a or b`
- `a**b` or `pow(a,b)` for $a^b$
- `a%b` or `remainder(a,b)` for $a\mod b $
- `exp(3)` for $e^3$
- `log(20)` for $\ln 20$
- `log(20,2)` for $\log_2 20$
   

In [11]:
arr=np.array([[1,2,3]])
print(np.exp(arr)) # don't use exp(arr), which is the built-in exp function and accepts only real-valued input
print(5/2) #floating point division
print(5//2) #integer division

[[ 2.71828183  7.3890561  20.08553692]]
2.5
2


### Matrix opertion
- Remember that in Python, +,-,*, ** , / are all elementwise!
    - Note that ** here is to elementwise exponentiation
- Also, `axis=0` is the columns, `axis=1` is rows!
- Ways to do matrix multiplication:
    - `dot(A,B)`
    - `A.dot(B)`
    - `matmul(A,B)`
- Transpose of $A$: A.T
- Trace: `trace(A)`
- Sum of each column or row: `A.sum(axis=0)` or `A.sum(axis=1)`
- Sum of all elements: `A.sum()`
- Frobenius Norm of matrix: `norm(A)`, where $A$ can be vector. 
- Inverse: `linalg.inv(A)`
- Determinant: `linalg.det(A)`
- Rank: `linalg.matrix_rank(A)`
- Matrix power: `linalg.matrix_power(A)`
- Solve $Ax=b$: `linalg.solve(A,b)`
- Eigen-decomposition: `D,V=linalg.eig(A)`

In [12]:
A=np.array([[1,2,3],[4,5,6]])
print(A)
print(A.sum(axis=0)) #along each row
print(A.sum(axis=1)) #along each row
print("shape of A = " + str(np.shape(A)))
print("shape of A[0] = " + str(A.shape[0]))
print("shape of A[1] = " + str(A.shape[1]))
B=np.array([[1,2],[3,4],[5,6]])
C=np.dot(A,B)
print(np.linalg.inv(C)) # linalg is part of numpy!

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]
shape of A = (2, 3)
shape of A[0] = 2
shape of A[1] = 3
[[ 1.77777778 -0.77777778]
 [-1.36111111  0.61111111]]


### 1.4 - Normalizing rows

Another common technique we use in Machine Learning and Deep Learning is to normalize our data. It often leads to a better performance because gradient descent converges faster after normalization. Here, by normalization we mean changing x to $ \frac{x}{\| x\|} $ (dividing each row vector of x by its norm).

For example, if $$x = 
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{3}$$ then $$\| x\| = np.linalg.norm(x, axis = 1, keepdims = True) = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4} $$and        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}$$ Note that you can divide matrices of different sizes and it works fine: this is called broadcasting and you're going to learn about it in part 5.


**Exercise**: Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x, each row of x should be a vector of unit length (meaning length 1).

In [13]:
def normalizeRows(X):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    X_norm = np.linalg.norm(X, ord=2, axis=1, keepdims=True)
    # here, `ord=2` means $L_2$ norm, `axis=1` means across columns, `keepdims=True` means 
    
    #print(X_norm.shape)
    X=X/X_norm
    
    return X 

In [14]:
X = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("original X = " +str(X))
print("normalizeRows(X) = " + str(normalizeRows(X)))

original X = [[0 3 4]
 [1 6 4]]
normalizeRows(X) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


### 2.1 Implement the L1 and L2 loss functions

**Exercise**: Implement the numpy vectorized version of the L1 loss. You may find the function abs(x) (absolute value of x) useful.

**Reminder**:
- The loss is used to evaluate the performance of your model. The bigger your loss is, the more different your predictions ($ \hat{y} $) are from the true values ($y$). In deep learning, you use optimization algorithms like Gradient Descent to train your model and to minimize the cost.
- L1 loss is defined as:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$

**Exercise**: Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder, if $x = [x_1, x_2, ..., x_n]$, then `np.dot(x,x)` = $\sum_{j=0}^n x_j^{2}$. 

- L2 loss is defined as $$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [15]:
def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    loss=np.abs(y-yhat)
    loss=np.sum(loss)
    return loss


def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    loss=np.dot(y-yhat,y-yhat)
    loss=np.sum(loss)
    return loss

In [16]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

print("L2 = " + str(L2(yhat,y)))

L1 = 1.1
L2 = 0.43


### sigmoid function, np.exp(), and sigmoid gradient ###

**Reminder**:
$sigmoid(x) = \frac{1}{1+e^{-x}}$ is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.

**Exercise**: Implement the sigmoid function using numpy. 

**Instructions**: x could now be either a real number, a vector, or a matrix. The data structures we use in numpy to represent these shapes (vectors, matrices...) are called numpy arrays. You don't need to know more for now.
$$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

**Exercise**: Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is: $$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$
You often code this function in two steps:
1. Set s to be the sigmoid of x. You might find your sigmoid(x) function useful.
2. Compute $\sigma'(x) = s(1-s)$

In [17]:
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    s=1/(1+np.exp(-x))
    return s

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    s=sigmoid(x)
    return s*(1-s) #elemenwise multipliaction, if s is matrix 
    

In [18]:
x = np.array([1, 2, 3])
print("original x = " +str(x))
print("sigmoid(x) = " +str(sigmoid(x)))
print ("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)) +"\n")

y=np.array([[1,2,3],[4,5,6]])
print("original y = " +str(y))
print("sigmoid(y) = " +str(sigmoid(y)))
print ("sigmoid_derivative(y) = " + str(sigmoid_derivative(y)))

original x = [1 2 3]
sigmoid(x) = [0.73105858 0.88079708 0.95257413]
sigmoid_derivative(x) = [0.19661193 0.10499359 0.04517666]

original y = [[1 2 3]
 [4 5 6]]
sigmoid(y) = [[0.73105858 0.88079708 0.95257413]
 [0.98201379 0.99330715 0.99752738]]
sigmoid_derivative(y) = [[0.19661193 0.10499359 0.04517666]
 [0.01766271 0.00664806 0.00246651]]


### Symbolic Math
- More info: http://www.scipy-lectures.org/advanced/sympy.html
- Rational number: `a=Rational(1,2)`
- Note that after using `Rational`, some constants (eg pi & exp(1)) will become symbols.
- Variable declaration: `x=Symbol('x')` and `y=Symbol('y')`
    -Then we can do standard algebric manipulation. EG: `x+y+x-y` and `(x+y)**2`
- Expansion: `expand((x+y)**5)`
- Simplication: `simplify((x+x*y)/x)` 
- Evaluating limit: The form is `limit(function, variable, point)`
    - EG: `limit(sin(x)/x, x, 0)`
    - EG: `limit(x, x, oo)`
    - EG: `limit(1/x, x, oo)`
- Taylor Series expension: The form is `series(expression, var)`
    - EG: `series(cos(x), x)`
    - EG: `series(1/cos(x), x)`
    - EG: `series(exp(x), x)`
- Equation solving: The form is `solve(expression, variable to be solve)
    - EG: `solve(x**4 - 1, x)`
    - EG: `solve([x + 5*y - 2, -3*x + 6*y - 15], [x, y])`

    
    
    

In [19]:
a=Rational(1,2)
print (a)
print (a+3)
print(pi*2)
(pi*2).evalf()
x=Symbol('x')
y=Symbol('y')
expand((x+y)**5)
simplify((x+x*y)/x)
limit(sin(x)/x, x, 0)
limit(1/x, x, oo)
series(cos(x), x)
#help Expr.series?
series(exp(x), x, 2)


NameError: name 'Rational' is not defined

### Symbolic Linear Algebra
- Symbolic matrix: We use `Matrix()` from sympy 
    - `A= matrix([[1,x],[y,1]])`
    - Note, however, that `array([[1,x],[y,1]])` will result in error!!! That is, we cannot create a symbolic matrix with `array`!
    - **Important** `Matrix([[1,x],[y,1]])` (with capital) from sympy is different from `matrix([[1,x],[y,1]])`  from numpy
- Matrix inverse: Use `A.inv()` from sympy
    
    
    


In [ ]:
A= Matrix([[1,x],[y,1]])
B= matrix([[1,x],[y,1]])
print (A) 
print (B)
print(A==B)
A**2
#B**2
print(A.inv())

In [ ]:
A=np.arange(12).reshape(3,4)
print(A)
x=np.array([[1,2,3]])
#x_norm = np.linalg.norm(x,ord=2,axis=1, keepdims=True)
x_norm = np.linalg.norm(x,ord=2,axis=1)
print(x_norm)
A/x_norm


### Comparison of time: for loop vs vectorization

In [21]:
import time

size_of_vec = 10
x1=range(size_of_vec)
x2=range(size_of_vec)

#x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
#x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]


### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
#print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print (str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
#print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print (str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")






#x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
#x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


0.0ms
0.0ms
elementwise multiplication = [ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
 ----- Computation time = 0.0ms
gdot = [21.98442052 16.28586694 23.97585151]
 ----- Computation time = 0.0ms
dot = 285
 ----- Computation time = 0.0ms
outer = [[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
 ----- Computation time = 0.0ms
elementwise multiplication = [ 0  1  4  9 16 25 36 49 64 81]
 ----- Computation time = 0.0ms
gdot = [21.98442052 16.28586694 23.97585151]
 ----- Computation time = 0.0ms


In [22]:
# Good implementation for comparing the time difference 

size_of_vec = 1000000

def forloop_version(a,b):
    result=0
    tic=time.time()
    for i in range(size_of_vec):
        result+=a[i]*b[i]
    toc=time.time()
    return result, 1000*(toc-tic)

def vectorization_version(a,b):
    result=0
    tic=time.time()
    result=np.dot(a,b)
    toc=time.time()
    return result, 1000*(toc-tic)

a=np.random.rand(size_of_vec)
b=np.random.rand(size_of_vec)
print("result of for loop version: " + str(forloop_version(a,b)))
print("result of vectorization version: " + str(vectorization_version(a,b)))


result of for loop version: (249904.62668922104, 250.1688003540039)
result of vectorization version: (249904.62668922194, 45.84956169128418)


### Pass by reference
- Note that np.array in Python is pass by reference!
- To avoid this issue, use `.copy` attribute


In [ ]:
x=3
x_copy=x
x_copy=4
print("x_copy = " + str(x_copy) + '\n')
print("x = " + str(x) + '\n')

A=np.zeros((3,3))
A_copy=A
A_copy[0,0]=10
print("A_copy = " + str(A_copy) + '\n')
print("A = " + str(A) + '\n')

B=np.zeros((3,3))
B_copy=B.copy()
B_copy[0,0]=20
print("B_copy = " + str(B_copy) + '\n')
print("B = " + str(B) + '\n')


# ETL

In [ ]:
# https://medium.com/analytics-vidhya/building-a-etl-pipeline-226656a22f6d
# %%
import requests
import pandas as pd
import numpy as np
import os
import sqlite3
from tqdm.auto import tqdm

# CONSTANT VALUES
OWNER = 'CSSEGISandData'
REPO = 'COVID-19'
PATH = 'csse_covid_19_data/csse_covid_19_daily_reports'
URL = f'https://api.github.com/repos/{OWNER}/{REPO}/contents/{PATH}'
print(f'Downloading paths from {URL}')


download_urls = []
response = requests.get(URL)
for data in tqdm(response.json()):
    if data['name'].endswith('.csv'):
        download_urls.append(data['download_url'])


# List of labels to be renamed
relabel = {
    # 'Last Update': 'Last_Update',
    'Country/Region': 'Country_Region',
    'Lat': 'Latitude',
    'Long_': 'Longitude',
    'Province/State': 'Province_State',
}


def factor_dataframe(dat, filename):
    """ Refactor the dataframe to be uploaded into a SQL database
    as a pandas DataFrame
    """
    # rename labels
    for label in dat:
        if label in relabel:
            dat = dat.rename(columns = {label: relabel[label]})
    
    # return a dataframe with these parameters
    labels = ['Province_State', 'Country_Region', 'Last_Update', 'Confirmed', 'Deaths', 'Recovered']
    # filename is datetime
    if 'Last_Update' not in dat:
        dat['Last_Update'] = pd.to_datetime(filename)

    # replace columns not in dataframe with nan
    for label in labels:
        if label not in dat:
            dat[label] = np.nan

    return dat[labels]

def upload_to_sql(filenames, db_name, debug=False):
    """ Given a list of paths, upload to a database
    """
    conn = sqlite3.connect(f"{db_name}.db")
    
    if debug:
        print("Uploading into database")
    for i, file_path in tqdm(list(enumerate(filenames))):
        
        dat = pd.read_csv(file_path)

        # rename labels
        filename = os.path.basename(file_path).split('.')[0]
        dat = factor_dataframe(dat, filename)

        # write records to sql database
        if i == 0: # if first entry, and table name already exist, replace
            dat.to_sql(db_name, con=conn, index = False, if_exists='replace')
        else: # otherwise append to current table given db_name
            dat.to_sql(db_name, con=conn, index = False, if_exists='append')


# upload into sql database
upload_to_sql(download_urls, 'example', debug=True)
# %%
download_urls
URL
# %%
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="yourusername",
  password="yourpassword"
)

mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE mydatabase")
# %%
conn = mysql.connector.connect(user='root', password='password', host='127.0.0.1')


# %%
import requests
import pandas as pd
import numpy as np
import os
import sqlite3
# %%
URL = r'https://api.github.com/repos/CSSEGISandData/COVID-19/contents/csse_covid_19_data/csse_covid_19_daily_reports'
print(f'Downloading covid-19 data from {URL}...')

response = requests.get(URL)
urls_csv = [file['download_url'] for file in response.json() if file['name'].endswith('.csv')]
# %%
