In [1]:
from ds_preamble import *

In [2]:
df = pd.read_csv('mdata.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66836 entries, 0 to 66835
Data columns (total 31 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   contract_no     66836 non-null  int64  
 1   ins_idn         66836 non-null  int64  
 2   age_5           66836 non-null  int64  
 3   gender          66836 non-null  object 
 4   is_smoker       66836 non-null  int64  
 5   weight          64237 non-null  object 
 6   height          64813 non-null  object 
 7   occ_life_cover  65910 non-null  object 
 8   g_self_v1       66135 non-null  float64
 9   g_self_v2       66130 non-null  float64
 10  g_self_v3       66068 non-null  float64
 11  g_self_v4       66085 non-null  float64
 12  g_self_v5       66135 non-null  float64
 13  g_self_v6       66102 non-null  float64
 14  g_self_v7       66130 non-null  float64
 15  g_self_v8       66150 non-null  float64
 16  m_exam_v1_i     9249 non-null   float64
 17  m_exam_v2_i     9238 non-null  

In [3]:
df.decision.value_counts()

std        57479
substd      6015
decline     3342
Name: decision, dtype: int64

In [4]:
df.isna().mean().sort_values(ascending=False)[lambda x: x>0]


m_exam_v7_3       0.964735
m_exam_v8_3       0.964660
m_exam_v7_2       0.930771
m_exam_v8_2       0.930756
m_exam_v7_1       0.861811
m_exam_v10_cm     0.861796
m_exam_v2_i       0.861781
m_exam_v5_i       0.861766
m_exam_v3_i       0.861706
m_exam_v9_cm      0.861631
m_exam_v8_1       0.861616
m_exam_v1_i       0.861616
m_exam_v6_i       0.861542
m_exam_v4_i       0.861362
weight            0.038886
height            0.030268
occ_life_cover    0.013855
g_self_v3         0.011491
g_self_v4         0.011236
g_self_v6         0.010982
g_self_v7         0.010563
g_self_v2         0.010563
g_self_v5         0.010488
g_self_v1         0.010488
g_self_v8         0.010264
dtype: float64

In [33]:
# df.weight.str.extract('(\d+)')

# res = []
# for s in df.weight:

d1 = df.weight.str.extract('(\d+)').astype('float').iloc[:,0]
d2 = df.weight.str.contains('lb|lbs', case=False)

# pd.Series(d1)
# d2
# d2






# d1.apply(lambda x: x+3)




# d1
# d2

# d1.values
# np.where(d2.values[:2], d1.values[:2]*0.453592, d1.values[:2])






# df.weight.sample(30)
# df.height.sample(30)
# df.weight.str.contains?

0        160.0
1         64.0
2         58.0
3         56.0
4         69.0
         ...  
66831    139.0
66832    147.0
66833    119.0
66834    143.0
66835    132.0
Name: 0, Length: 66836, dtype: float64

0         True
1        False
2        False
3        False
4        False
         ...  
66831     True
66832     True
66833     True
66834     True
66835     True
Name: weight, Length: 66836, dtype: object

In [28]:
x,y,c = np.array([3.1, 1.2, 1.3, 5.4, 1.5]), np.array([2.1, 2.2, 2.3, 2.4, 2.5]), np.array([True, False, True, True, False])
print(np.where(c,x,y)) # [3.1 2.2 1.3 5.4 2.5]
print(np.where(x>y,x,y)) # [3.1 2.2 2.3 5.4 2.5]. same as np.maximum(x,y)
print(np.where(x<y,x,y)) # [2.1 1.2 1.3 2.4 1.5]. same as np.minimum(x,y) 


c = d2.values[:2]
x = d1.values[:2]*0.453592
y = d1.values[:2]

c.shape
x.shape


# c
# x
# y

# c=d2.to_list()[:2]
# x=d1.to_list()[:2]
# y=d1.to_list()[:2]

# print(np.where(c,x,y))



[3.1 2.2 1.3 5.4 2.5]
[3.1 2.2 2.3 5.4 2.5]
[2.1 1.2 1.3 2.4 1.5]


(2,)

(2, 1)

In [ ]:
df.bmi = 