In [1]:
from ds_preamble import *

In [2]:
df = pd.read_csv('mdata.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66836 entries, 0 to 66835
Data columns (total 31 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   contract_no     66836 non-null  int64  
 1   ins_idn         66836 non-null  int64  
 2   age_5           66836 non-null  int64  
 3   gender          66836 non-null  object 
 4   is_smoker       66836 non-null  int64  
 5   weight          64237 non-null  object 
 6   height          64813 non-null  object 
 7   occ_life_cover  65910 non-null  object 
 8   g_self_v1       66135 non-null  float64
 9   g_self_v2       66130 non-null  float64
 10  g_self_v3       66068 non-null  float64
 11  g_self_v4       66085 non-null  float64
 12  g_self_v5       66135 non-null  float64
 13  g_self_v6       66102 non-null  float64
 14  g_self_v7       66130 non-null  float64
 15  g_self_v8       66150 non-null  float64
 16  m_exam_v1_i     9249 non-null   float64
 17  m_exam_v2_i     9238 non-null  

In [3]:
df.decision.value_counts()

std        57479
substd      6015
decline     3342
Name: decision, dtype: int64

In [4]:
df.isna().mean().sort_values(ascending=False)[lambda x: x>0]


m_exam_v7_3       0.964735
m_exam_v8_3       0.964660
m_exam_v7_2       0.930771
m_exam_v8_2       0.930756
m_exam_v7_1       0.861811
m_exam_v10_cm     0.861796
m_exam_v2_i       0.861781
m_exam_v5_i       0.861766
m_exam_v3_i       0.861706
m_exam_v9_cm      0.861631
m_exam_v8_1       0.861616
m_exam_v1_i       0.861616
m_exam_v6_i       0.861542
m_exam_v4_i       0.861362
weight            0.038886
height            0.030268
occ_life_cover    0.013855
g_self_v3         0.011491
g_self_v4         0.011236
g_self_v6         0.010982
g_self_v7         0.010563
g_self_v2         0.010563
g_self_v5         0.010488
g_self_v1         0.010488
g_self_v8         0.010264
dtype: float64

In [41]:
# df.weight.str.extract('(\d+)')

# res = []
# for s in df.weight:

# d1 = df.weight.str.extract('(\d+)').astype('float').iloc[:,0]
d1 = df.weight.str.extract('(^\d*)').astype('float').iloc[:,0]
d2 = df.weight.str.contains('lb|lbs', case=False)
np.where(d2, d1*0.453592, d1)
df.weight=np.where(d2, d1*0.453592, d1)

AttributeError: Can only use .str accessor with string values!

In [47]:
# d1 = df.weight.str.extract('(^\d*)').astype('float').iloc[:,0]
# d2 = df.weight.str.contains('lb|lbs', case=False)
# np.where(d2, d1*0.453592, d1)
# df.weight=np.where(d2, d1*0.453592, d1)
# in, cm, m, 

df.height.sample(50)
# df.weight.isna().sum()

44426    64.57 In 
39859     148.1CM 
43389        1.7 M
48875     68.54In 
14184    172.9 cm 
60919     66.65 IN
45258      168.1cm
32756       1.74m 
53209     168.1cm 
51522     149.5Cm 
23960     159.3Cm 
10011       1.57M 
8768          1.7m
52424       1.57 m
63399        1.63m
64054     71.26in 
38062     164.7 CM
32739      56.85IN
22896     152.8CM 
3186      165.7cm 
30648      156.6cm
49047       1.52 m
37847       171 cm
56512     166.6Cm 
48307        1.53m
466        72.44IN
17653       1.7 m 
34592        1.52m
42621      62.68in
31463    162.2 Cm 
19338    68.58 In 
27695      1.57 m 
54604      62.2IN 
19221      68.5 in
911      167.9 Cm 
3754      65.12IN 
27165     163.4 CM
38668       1.41 M
40870     168.4 cm
12268    68.46 in 
41416      166.1CM
29052     61.54IN 
49800     62.44in 
16337      69.72IN
48242          NaN
44627          NaN
34708        168cm
32607     175.4 cm
21811    165.3 cm 
18116      1.66 m 
Name: height, dtype: object

In [72]:
cols = [col for col in df if col.startswith('g_self_')]
df[cols] = df[cols].fillna(0)
# df.filter(regex='^g_self_', axis = 1).fillna(0)
# df.iloc[:, df.columns.str.startswith('g_self_')]


In [94]:
cols = [col for col in df if col.startswith('m_exam_') and col.endswith('_i')]
df[cols] = df[cols].fillna('unk')
# df.filter(regex='^m_exam_.*_i', axis = 1)






m_exam_v1_i    0
m_exam_v2_i    0
m_exam_v3_i    0
m_exam_v4_i    0
m_exam_v5_i    0
m_exam_v6_i    0
dtype: int64

In [ ]:
df['occ_life_cover'] = fillna('STD')

In [28]:
x,y,c = np.array([3.1, 1.2, 1.3, 5.4, 1.5]), np.array([2.1, 2.2, 2.3, 2.4, 2.5]), np.array([True, False, True, True, False])
print(np.where(c,x,y)) # [3.1 2.2 1.3 5.4 2.5]
print(np.where(x>y,x,y)) # [3.1 2.2 2.3 5.4 2.5]. same as np.maximum(x,y)
print(np.where(x<y,x,y)) # [2.1 1.2 1.3 2.4 1.5]. same as np.minimum(x,y) 


c = d2.values[:2]
x = d1.values[:2]*0.453592
y = d1.values[:2]

c.shape
x.shape


# c
# x
# y

# c=d2.to_list()[:2]
# x=d1.to_list()[:2]
# y=d1.to_list()[:2]

# print(np.where(c,x,y))



[3.1 2.2 1.3 5.4 2.5]
[3.1 2.2 2.3 5.4 2.5]
[2.1 1.2 1.3 2.4 1.5]


(2,)

(2, 1)

In [ ]:
df.bmi = 