In [1]:
from ds_preamble import *

In [2]:
df = pd.read_csv('mdata.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66836 entries, 0 to 66835
Data columns (total 31 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   contract_no     66836 non-null  int64  
 1   ins_idn         66836 non-null  int64  
 2   age_5           66836 non-null  int64  
 3   gender          66836 non-null  object 
 4   is_smoker       66836 non-null  int64  
 5   weight          64237 non-null  object 
 6   height          64813 non-null  object 
 7   occ_life_cover  65910 non-null  object 
 8   g_self_v1       66135 non-null  float64
 9   g_self_v2       66130 non-null  float64
 10  g_self_v3       66068 non-null  float64
 11  g_self_v4       66085 non-null  float64
 12  g_self_v5       66135 non-null  float64
 13  g_self_v6       66102 non-null  float64
 14  g_self_v7       66130 non-null  float64
 15  g_self_v8       66150 non-null  float64
 16  m_exam_v1_i     9249 non-null   float64
 17  m_exam_v2_i     9238 non-null  

In [3]:
df.decision.value_counts()

std        57479
substd      6015
decline     3342
Name: decision, dtype: int64

In [4]:
df.isna().mean().sort_values(ascending=False)[lambda x: x>0]


m_exam_v7_3       0.964735
m_exam_v8_3       0.964660
m_exam_v7_2       0.930771
m_exam_v8_2       0.930756
m_exam_v7_1       0.861811
m_exam_v10_cm     0.861796
m_exam_v2_i       0.861781
m_exam_v5_i       0.861766
m_exam_v3_i       0.861706
m_exam_v9_cm      0.861631
m_exam_v8_1       0.861616
m_exam_v1_i       0.861616
m_exam_v6_i       0.861542
m_exam_v4_i       0.861362
weight            0.038886
height            0.030268
occ_life_cover    0.013855
g_self_v3         0.011491
g_self_v4         0.011236
g_self_v6         0.010982
g_self_v7         0.010563
g_self_v2         0.010563
g_self_v5         0.010488
g_self_v1         0.010488
g_self_v8         0.010264
dtype: float64

In [39]:
# df.weight.str.extract('(\d+)')

# res = []
# for s in df.weight:

# d1 = df.weight.str.extract('(\d+)').astype('float').iloc[:,0]
d1 = df.weight.str.extract('(^\d*)').astype('float').iloc[:,0]
d2 = df.weight.str.contains('lb|lbs', case=False)
np.where(d2, d1*0.453592, d1)
df

array([72.57472 , 64.      , 58.      , ..., 53.977448, 64.863656,
       59.874144])

contract_no  ins_idn  age_5 gender  is_smoker       weight     height  \
0            95552    68024     25      M          0    160.6 lbs  170.2 Cm    
1           561363   453625     40      M          0       64.4KG  168.1 cm    
2            33417   256753     40      F          1      58.1 kg        NaN   
3           546761   460543     50      F          0       56.6Kg   158.1 Cm   
4            91520   432711     55      F          0     69.9 kg    64.09 In   
...            ...      ...    ...    ...        ...          ...        ...   
66831       572249   298299     35      M          0   139.48 lbs    65.43IN   
66832       165801   400958     30      M          0   147.84LBS    174.6 cm   
66833       659819   229161     30      M          0     119.9LBS      70IN    
66834       640241   174731     40      M          0  143.22 lbs    65.71In    
66835       458068   489538     50      F          1   132.66 Lbs   63.31In    

      occ_life_cover  g_self_v1  g_self_v2  ...  m_exam_v6_i  m_exam_v9_cm  \
0                STD        0.0        0.0  ...          NaN           NaN   
1               +2/M        0.0        0.0  ...          0.0         83.96   
2                 IC        0.0        0.0  ...          NaN           NaN   
3               +2/M        0.0        0.0  ...          NaN           NaN   
4               +2/M        0.0        0.0  ...          NaN           NaN   
...              ...        ...        ...  ...          ...           ...   
66831             IC        0.0        0.0  ...          NaN           NaN   
66832           +2/M        0.0        0.0  ...          NaN           NaN   
66833           +2/M        0.0        0.0  ...          NaN           NaN   
66834           +2/M        0.0        0.0  ...          NaN           NaN   
66835             IC        0.0        0.0  ...          NaN           NaN   

       m_exam_v10_cm  m_exam_v7_1  m_exam_v7_2  m_exam_v7_3  m_exam_v8_1  \
0                NaN          NaN          NaN          NaN          NaN   
1              87.57       125.94          NaN          NaN        80.73   
2                NaN          NaN          NaN          NaN          NaN   
3                NaN          NaN          NaN          NaN          NaN   
4                NaN          NaN          NaN          NaN          NaN   
...              ...          ...          ...          ...          ...   
66831            NaN          NaN          NaN          NaN          NaN   
66832            NaN          NaN          NaN          NaN          NaN   
66833            NaN          NaN          NaN          NaN          NaN   
66834            NaN          NaN          NaN          NaN          NaN   
66835            NaN          NaN          NaN          NaN          NaN   

       m_exam_v8_2  m_exam_v8_3  decision  
0              NaN          NaN       std  
1              NaN          NaN       std  
2              NaN          NaN       std  
3              NaN          NaN    substd  
4              NaN          NaN       std  
...            ...          ...       ...  
66831          NaN          NaN       std  
66832          NaN          NaN       std  
66833          NaN          NaN    substd  
66834          NaN          NaN       std  
66835          NaN          NaN       std  

[66836 rows x 31 columns]

In [28]:
x,y,c = np.array([3.1, 1.2, 1.3, 5.4, 1.5]), np.array([2.1, 2.2, 2.3, 2.4, 2.5]), np.array([True, False, True, True, False])
print(np.where(c,x,y)) # [3.1 2.2 1.3 5.4 2.5]
print(np.where(x>y,x,y)) # [3.1 2.2 2.3 5.4 2.5]. same as np.maximum(x,y)
print(np.where(x<y,x,y)) # [2.1 1.2 1.3 2.4 1.5]. same as np.minimum(x,y) 


c = d2.values[:2]
x = d1.values[:2]*0.453592
y = d1.values[:2]

c.shape
x.shape


# c
# x
# y

# c=d2.to_list()[:2]
# x=d1.to_list()[:2]
# y=d1.to_list()[:2]

# print(np.where(c,x,y))



[3.1 2.2 1.3 5.4 2.5]
[3.1 2.2 2.3 5.4 2.5]
[2.1 1.2 1.3 2.4 1.5]


(2,)

(2, 1)

In [ ]:
df.bmi = 